spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lab_manager?serverTimezone=UTC
    username: root
    password: yourpassword
  thymeleaf:
    cache: false # 关闭缓存
    web:
      resources:
        cache:
          period: 0